// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZKMY_7Lmp7umvEC6pzR6OZJfXPkAx1fs',
    appId: '1:701141584047:web:ff9f41c7ee8149d7a8ec5a',
    messagingSenderId: '701141584047',
    projectId: 'udemy-flutter-demo-b04d6',
    authDomain: 'udemy-flutter-demo-b04d6.firebaseapp.com',
    storageBucket: 'udemy-flutter-demo-b04d6.appspot.com',
    measurementId: 'G-5J4YZNK3CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VCvX6MBTQwJRApOCAqRHGLluVa3gzGE',
    appId: '1:701141584047:android:faa9fb148d3ec28fa8ec5a',
    messagingSenderId: '701141584047',
    projectId: 'udemy-flutter-demo-b04d6',
    storageBucket: 'udemy-flutter-demo-b04d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6E8BNX-7ANvwrPpQ5loka2IsrSNTIRrs',
    appId: '1:701141584047:ios:80396a7e664c48b9a8ec5a',
    messagingSenderId: '701141584047',
    projectId: 'udemy-flutter-demo-b04d6',
    storageBucket: 'udemy-flutter-demo-b04d6.appspot.com',
    iosClientId: '701141584047-nm8el7errv272dhoffv00j48f0agri2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyFlutterSns',
  );
}
